### ISSUE TITLE
Undo spawn after game restart by storing spawnActions object?

### ISSUE THREAD

**Issue by bjorno43** [Cooleyy/EasySpawner#10]
I know you're not planning to make an object remover mod, but I was wondering if it would be possible to store spawned objects in a database or maybe just a JSON file that can be loaded back in upon a restart? The mod could then have a list of "previously spawned objects" and you could just select and delete them again.

Unfortunately I'm not that familiar with Valheim modding, otherwise I'd be glad to do it myself an make a pull request. Hence I'm asking if you're willing to do this.

**Comment by Cooleyy** [comment]
Unfortunately its not that simple. Currently it just stores a reference to the gameobjects you spawn with the mod and whenever you close the game these references are meaningless. Storing them in a database would do nothing since when you restart the game those references wont work anymore. You would need a way to retrieve those exact objects again which is possible by storing info about those items, ( for example. Object name and Co-ordinates) but this is far more than I want to do for this mod.

**Comment by MSchmoecker** [comment]
Actually it seems possible, every `ZNetView` has a private `ZDO` which stores a unique id for the save file. But I agree with Cooleyy, it is much effort for such a small use case. And it already can be reverted in the same session.

**Comment by bjorno43** [comment]
> 
> 
> Actually it seems possible, every `ZNetView` has a private `ZDO` which stores a unique id for the save file. But I agree with Cooleyy, it is much effort for such a small use case. And it already can be reverted in the same session.

Ye I understand. For me, the 2 major use cases were the ability to make sky city builds on top of skulls (they have no gravity and allow building on top of them). Obviously in case of updates that would affect this, it would be useful to be able to delete the skulls as they cannot be destroyed. And the other use case would be the odd chance that a server (or your internet) crashes before you were able to remove something.
