### ISSUE TITLE
help ? 

### ISSUE THREAD

**Issue by Funky18229** [Cooleyy/EasySpawner#16]
I keep getting this message in the start up of the server, there are few other mods that do the same thing

[Warning:   BepInEx] Skipping [Easy Spawner 1.4.2] because of process filters (valheim.exe)

not sure why but if u have any insight on this,........please let me know.

**Comment by MSchmoecker** [comment]
This is because the server exe is named `valheim_server.exe` and therefore an optional process filter is stopping the mod to execute.  This mod is fully client-side and therefore doesn't need executing on the server, so you can just ignore this message. If one of the other mods need to be active on the server you have to message the responsible authors.
